language: python

python:
  - "3.6"

install:
  - pip install boto3
  - pip install codecov
  - pip install coverage
  - pip install pytz

script:
  - coverage run -m unittest discover

after_success:
  - codecov